#############################################################################
# Generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#  Sep 02, 2020 10:44:55 AM +03  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m46" -background #202020 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 999x761+481+53
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    menu $top.m46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    $top.m46 add command \
        -command {#} -label help 
    $top.m46 add cascade \
        -menu "$top.m46.men45" -command {{}} -label NewCascade 
    set site_3_0 $top.m46
    menu $site_3_0.men45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black -background #202020 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 21 -weight bold -slant italic -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text INPUT 
    vTcl:DefineAlias "$top.lab49" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab50 \
        -activebackground #f9f9f9 -activeforeground black -background #202020 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 21 -weight bold -slant italic -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text OUTPUT 
    vTcl:DefineAlias "$top.lab50" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd $top.scr54 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.scr54" "Scrolledtext1" vTcl:WidgetProc "Toplevel1" 1

    $top.scr54.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground blue \
        -selectforeground white \
        -width 10 \
        -wrap none
    label $top.lab55 \
        -activebackground #f9f9f9 -activeforeground black -background #202020 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 17 -weight bold -slant italic -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text OR 
    vTcl:DefineAlias "$top.lab55" "Label1_3" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd $top.scr58 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 125 
    vTcl:DefineAlias "$top.scr58" "Scrolledtext2" vTcl:WidgetProc "Toplevel1" 1

    $top.scr58.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground blue \
        -selectforeground white \
        -width 10 \
        -wrap none
    ttk::progressbar $top.tPr59 \
        -length 870 
    vTcl:DefineAlias "$top.tPr59" "TProgressbar1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab65 \
        -activebackground #f9f9f9 -activeforeground black -background #202020 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 21 -weight bold -slant italic -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text OPTIONS 
    vTcl:DefineAlias "$top.lab65" "Label1_4" vTcl:WidgetProc "Toplevel1" 1
    button $top.but67 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe Script} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Browse 
    vTcl:DefineAlias "$top.but67" "Button1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent68 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 184 
    vTcl:DefineAlias "$top.ent68" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $top.che69 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #202020 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor #ffffff -justify left -selectcolor #ffffff \
        -text Check -variable che69 
    vTcl:DefineAlias "$top.che69" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $top.che71 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #202020 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor #ffffff -justify left -selectcolor #ffffff \
        -text Check -variable che69 
    vTcl:DefineAlias "$top.che71" "Checkbutton1_5" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab73 \
        -activebackground #f9f9f9 -activeforeground black -background #202020 \
        -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI} -size 17 -weight bold -slant italic -underline 0 -overstrike 0} \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text {import a file} 
    vTcl:DefineAlias "$top.lab73" "Label1_2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but74 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe Script} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {copy all text} 
    vTcl:DefineAlias "$top.but74" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $top.but75 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe Script} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Save 
    vTcl:DefineAlias "$top.but75" "Button2_5" vTcl:WidgetProc "Toplevel1" 1
    button $top.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe Script} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Start 
    vTcl:DefineAlias "$top.but45" "Button1_3" vTcl:WidgetProc "Toplevel1" 1
    bind $top.but45 <Enter> {
        lambda e: xxx(e)
    }
    button $top.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffff00 -disabledforeground #a3a3a3 \
        -font {-family {Segoe Script} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Cancel 
    vTcl:DefineAlias "$top.but46" "Button1_4" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo45 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo45" "TCombobox1" vTcl:WidgetProc "Toplevel1" 1
    ttk::combobox $top.tCo46 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo46" "TCombobox1_1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab45 \
        -activebackground #ffffff -activeforeground #000000 \
        -background #400040 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground #ffffff -text {n emailes and n phones found} 
    vTcl:DefineAlias "$top.lab45" "Label2" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab49 \
        -in $top -x 0 -relx -0.026 -y 0 -rely -0.014 -width 0 -relwidth 0.208 \
        -height 0 -relheight 0.101 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx -0.011 -y 0 -rely 0.492 -width 0 -relwidth 0.209 \
        -height 0 -relheight 0.101 -anchor nw -bordermode ignore 
    place $top.scr54 \
        -in $top -x 0 -relx 0.158 -y 0 -rely 0.644 -width 0 -relwidth 0.307 \
        -height 0 -relheight 0.202 -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 0 -relx 0.587 -y 0 -rely 0.076 -width 0 -relwidth 0.168 \
        -height 0 -relheight 0.101 -anchor nw -bordermode ignore 
    place $top.scr58 \
        -in $top -x 0 -relx 0.056 -y 0 -rely 0.063 -width 0 -relwidth 0.571 \
        -height 0 -relheight 0.26 -anchor nw -bordermode ignore 
    place $top.tPr59 \
        -in $top -x 0 -relx 0.011 -y 0 -rely 0.891 -width 0 -relwidth 0.982 \
        -height 22 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab65 \
        -in $top -x 0 -relx -0.011 -y 0 -rely 0.328 -width 0 -relwidth 0.21 \
        -height 0 -relheight 0.101 -anchor nw -bordermode ignore 
    place $top.but67 \
        -in $top -x 0 -relx 0.813 -y 0 -rely 0.166 -height 33 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent68 \
        -in $top -x 0 -relx 0.745 -y 0 -rely 0.119 -width 184 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.che69 \
        -in $top -x 0 -relx 0.047 -y 0 -rely 0.445 -width 0 -relwidth 0.077 \
        -height 0 -relheight 0.037 -anchor nw -bordermode ignore 
    place $top.che71 \
        -in $top -x 0 -relx 0.281 -y 0 -rely 0.445 -width 0 -relwidth 0.078 \
        -height 0 -relheight 0.037 -anchor nw -bordermode ignore 
    place $top.lab73 \
        -in $top -x 0 -relx 0.717 -y 0 -rely 0.043 -width 0 -relwidth 0.212 \
        -height 0 -relheight 0.077 -anchor nw -bordermode ignore 
    place $top.but74 \
        -in $top -x 0 -relx 0.824 -y 0 -rely 0.631 -width 126 -relwidth 0 \
        -height 43 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but75 \
        -in $top -x 0 -relx 0.824 -y 0 -rely 0.76 -width 126 -relwidth 0 \
        -height 43 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but45 \
        -in $top -x 0 -relx 0.801 -y 0 -rely 0.943 -width 98 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 0 -relx 0.619 -y 0 -rely 0.943 -width 98 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tCo45 \
        -in $top -x 0 -relx 0.269 -y 0 -rely 0.483 -width 0 -relwidth 0.102 \
        -height 0 -relheight 0.02 -anchor nw -bordermode ignore 
    place $top.tCo46 \
        -in $top -x 0 -relx 0.035 -y 0 -rely 0.483 -width 0 -relwidth 0.102 \
        -height 0 -relheight 0.019 -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 0 -relx 0.149 -y 0 -rely 0.854 -width 0 -relwidth 0.208 \
        -height 0 -relheight 0.034 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

