#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 22, 2020 03:04:52 PM +03  platform: Windows NT

import sys,threading
from docx import Document
import Phonmail_extractor_app
import fitz  # this is pymupdf
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def convertDocxToText(path):
    docxFilename = path;document = Document(docxFilename)
    output = ""
    for para in document.paragraphs: 
        output = output + para.text + "\n"
    return output

def convertPdfToText(path):
    #tika.initVM()
    with fitz.open(path) as doc:
        text = ""
        for page in doc:
            text += page.getText()

    return(text)
        

# def fake_convertPdfToText(path):
#     s = threading.Thread(target=convertPdfToText(path))
#     s.start()




language_dict = [{"input":"INPUT","output":"OUTPUT"},{"input":"المدخلات","output":"المخرجات"}]
def set_Tk_var():
    global che69,che70,combobox,combobox2, L2,L3,L4,B1
    che69 = tk.IntVar(value = 1)
    che70 = tk.IntVar(value = 1)
    combobox = tk.StringVar()
    combobox2 = tk.StringVar()    
    
    L2 = tk.StringVar(value="OUTPUT")
    L3 = tk.StringVar(value="OPTIONS")
    L4 = tk.StringVar(value="OR")
    B1 = tk.StringVar(value = "Browse")



def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def xxx(p1):
    print('Phonmail_extractor_support.xxx')
    sys.stdout.flush()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Phonmail_extractor_app
    Phonmail_extractor_app.vp_start_gui()




